# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: soma.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='soma.proto',
  package='soma',
  syntax='proto3',
  serialized_pb=_b('\n\nsoma.proto\x12\x04soma\" \n\x06number\x12\n\n\x02n1\x18\x01 \x01(\x05\x12\n\n\x02n2\x18\x02 \x01(\x05\"\x11\n\x04soma\x12\t\n\x01s\x18\x01 \x01(\x05\x32.\n\x04Send\x12&\n\x08realizar\x12\x0c.soma.number\x1a\n.soma.soma\"\x00\x42*\n\x15io.grpc.examples.somaB\tsomaProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_NUMBER = _descriptor.Descriptor(
  name='number',
  full_name='soma.number',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n1', full_name='soma.number.n1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n2', full_name='soma.number.n2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=52,
)


_SOMA = _descriptor.Descriptor(
  name='soma',
  full_name='soma.soma',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='s', full_name='soma.soma.s', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=71,
)

DESCRIPTOR.message_types_by_name['number'] = _NUMBER
DESCRIPTOR.message_types_by_name['soma'] = _SOMA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

number = _reflection.GeneratedProtocolMessageType('number', (_message.Message,), dict(
  DESCRIPTOR = _NUMBER,
  __module__ = 'soma_pb2'
  # @@protoc_insertion_point(class_scope:soma.number)
  ))
_sym_db.RegisterMessage(number)

soma = _reflection.GeneratedProtocolMessageType('soma', (_message.Message,), dict(
  DESCRIPTOR = _SOMA,
  __module__ = 'soma_pb2'
  # @@protoc_insertion_point(class_scope:soma.soma)
  ))
_sym_db.RegisterMessage(soma)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\025io.grpc.examples.somaB\tsomaProtoP\001\242\002\003HLW'))

_SEND = _descriptor.ServiceDescriptor(
  name='Send',
  full_name='soma.Send',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=73,
  serialized_end=119,
  methods=[
  _descriptor.MethodDescriptor(
    name='realizar',
    full_name='soma.Send.realizar',
    index=0,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_SOMA,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SEND)

DESCRIPTOR.services_by_name['Send'] = _SEND

# @@protoc_insertion_point(module_scope)
