# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import soma_pb2 as soma__pb2


class SendStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.realizar = channel.unary_unary(
        '/soma.Send/realizar',
        request_serializer=soma__pb2.number.SerializeToString,
        response_deserializer=soma__pb2.soma.FromString,
        )


class SendServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def realizar(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SendServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'realizar': grpc.unary_unary_rpc_method_handler(
          servicer.realizar,
          request_deserializer=soma__pb2.number.FromString,
          response_serializer=soma__pb2.soma.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'soma.Send', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
